#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xgboost
Version  : 1.2.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/2a/8f/3b21e1a65ef54b1f536f5e31e6bae1eff72ab9e08655743a7a5435ce71fc/xgboost-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2a/8f/3b21e1a65ef54b1f536f5e31e6bae1eff72ab9e08655743a7a5435ce71fc/xgboost-1.2.0.tar.gz
Summary  : XGBoost Python Package
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: xgboost-license = %{version}-%{release}
Requires: xgboost-python = %{version}-%{release}
Requires: xgboost-python3 = %{version}-%{release}
Requires: dask
Requires: distributed
Requires: graphviz
Requires: matplotlib
Requires: numpy
Requires: pandas
Requires: scikit-learn
Requires: scipy
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : dask
BuildRequires : distributed
BuildRequires : graphviz
BuildRequires : matplotlib
BuildRequires : numpy
BuildRequires : pandas
BuildRequires : scikit-learn
BuildRequires : scipy
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
XGBoost Python Package
        ======================
        
        |PyPI version|
        
        Installation
        ============

%package dev
Summary: dev components for the xgboost package.
Group: Development
Provides: xgboost-devel = %{version}-%{release}
Requires: xgboost = %{version}-%{release}

%description dev
dev components for the xgboost package.


%package license
Summary: license components for the xgboost package.
Group: Default

%description license
license components for the xgboost package.


%package python
Summary: python components for the xgboost package.
Group: Default
Requires: xgboost-python3 = %{version}-%{release}

%description python
python components for the xgboost package.


%package python3
Summary: python3 components for the xgboost package.
Group: Default
Requires: python3-core
Provides: pypi(xgboost)
Requires: pypi(numpy)
Requires: pypi(scipy)

%description python3
python3 components for the xgboost package.


%prep
%setup -q -n xgboost-1.2.0
cd %{_builddir}/xgboost-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1598286760
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xgboost
cp %{_builddir}/xgboost-1.2.0/xgboost/LICENSE %{buildroot}/usr/share/package-licenses/xgboost/4d98c20884442064704475a2c7092515382cfe48
cp %{_builddir}/xgboost-1.2.0/xgboost/dmlc-core/LICENSE %{buildroot}/usr/share/package-licenses/xgboost/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/xgboost-1.2.0/xgboost/rabit/LICENSE %{buildroot}/usr/share/package-licenses/xgboost/6f755c9a3e0bbbfda2f9a37a7102e0606ea145f5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/any.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/array_view.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/base.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/blockingconcurrentqueue.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/build_config_default.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/common.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/concurrency.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/concurrentqueue.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/config.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/data.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/endian.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/filesystem.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/input_split_shuffle.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/io.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/json.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/logging.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/lua.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/memory.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/memory_io.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/omp.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/optional.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/parameter.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/recordio.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/registry.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/serializer.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/strtonum.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/thread_group.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/thread_local.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/threadediter.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/timer.h
/usr/lib/python3.8/site-packages/xgboost/dmlc-core/include/dmlc/type_traits.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/base.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/c_api.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/data.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/feature_map.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/gbm.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/generic_parameters.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/host_device_vector.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/json.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/json_io.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/learner.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/linear_updater.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/logging.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/metric.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/model.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/objective.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/parameter.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/predictor.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/span.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/tree_model.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/tree_updater.h
/usr/lib/python3.8/site-packages/xgboost/include/xgboost/version_config.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/base.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/c_api.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/engine.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/io.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/rabit-inl.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/socket.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/thread_local.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/timer.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/internal/utils.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/rabit.h
/usr/lib/python3.8/site-packages/xgboost/rabit/include/rabit/serializable.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xgboost/4d98c20884442064704475a2c7092515382cfe48
/usr/share/package-licenses/xgboost/6f755c9a3e0bbbfda2f9a37a7102e0606ea145f5
/usr/share/package-licenses/xgboost/92170cdc034b2ff819323ff670d3b7266c8bffcd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
